
-- Migration to add vote counts and metadata to scrutins
ALTER TABLE scrutins ADD COLUMN IF NOT EXISTS pour INTEGER DEFAULT 0;
ALTER TABLE scrutins ADD COLUMN IF NOT EXISTS contre INTEGER DEFAULT 0;
ALTER TABLE scrutins ADD COLUMN IF NOT EXISTS abstention INTEGER DEFAULT 0;
ALTER TABLE scrutins ADD COLUMN IF NOT EXISTS non_votant INTEGER DEFAULT 0;
ALTER TABLE scrutins ADD COLUMN IF NOT EXISTS code_organe VARCHAR(50);
ALTER TABLE scrutins ADD COLUMN IF NOT EXISTS title VARCHAR(1000);
